TCA:
  Types:
    default:
      description: string
      displayCond: string|array
      exclude: boolean
      label: string
      l10n_display: string
      l10n_mode: string
      onChange: string

    check:
      config:
        type: check
        cols: integer
        renderType:
          - checkboxToggle
          - checkboxLabeledToggle
        default: integer
        eval:
          - maximumRecordsChecked
          - maximumRecordsCheckedInPid
        items: array
        itemsProcFunc: string
        readOnly: boolean

    flex:

    group:

    imageManipulation:

    inline:

    input:

    none:

    passthrough:

    radio:

    select:

    slug:

    text:

    user: